server:
  port: 10001
spring:
  application:
    name: config-client
  cloud:
    config:
      label: master
      profile: config-client-dev
      uri: http://localhost:9501/
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:9500/eureka/
