eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9500/eureka/
spring:
  application:
    name: service-feign
  zipkin:
    base-url: http://localhost:20000
    sleuth:
      sampler:
      percentage: 1.0

server:
  port: 11000
