server:
  port: 10007
spring:
  application:
     name: config-client
  rabbitmq:
    addresses: 192.168.48.51:5672
    username: admin
    password: passwd
    publisher-confirms: true
    virtual-host: /
#    name: eureka-client
  cloud:
    config:
      label: master
      profile: dev
      #uri: http://localhost:8888/
      discovery:
        enabled: true
        serviceId: config-server
management:
  security:
    enabled: false

eureka:
  instance:
#    instance-id: ${spring.cloud.client.ipAddress}:${server.port} #设置实例的ID为ip:port
#    lease-renewal-interval-in-seconds: 5 #心跳时间，即服务续约间隔时间（缺省为30s）
#    lease-expiration-duration-in-seconds: 15 #发呆时间，即服务续约到期时间（缺省为90s）
  client:
    serviceUrl:
      defaultZone: http://localhost:9500/eureka/
#    healthcheck:
#      enabled: true